apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tee-reactapp-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/babsontimie/tee-react-app-k8s.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

