apiVersion: apps/v1
kind: Deployment
metadata:
  name: tee-reactapp-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tee-reactapp-api
  template:
    metadata:
      labels:
        app: tee-reactapp-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: tee-reactapp-api
          image: ghcr.io/babsontimie/tee-react-app-k8s:d216e2ab76125fa7b94135ebfcae207476ffdb8c
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: tee-reactapp-api
  namespace: dev
spec:
  selector:
    app: tee-reactapp-api
  ports:
    - port: 8085
      targetPort: 80
  type: NodePort
